### ISSUE TITLE
mojofailure error

### ISSUE THREAD

**Issue by lorenzoromani1983** [visallo/visallo#1329]
Good morning,

I am trying to run Visallo on windows, however I have never been able to install it. While on Mac/Ubuntu it is working, in my company we run windows.
I get this error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project visallo-client-api: Compilation failure
[ERROR] /C:/Users/utente-05/visallo/web/client-api/src/main/java/org/visallo/web/clientapi/util/ObjectMapperFactory.java:[25,20] reference to Module is ambiguous
[ERROR]   both class com.fasterxml.jackson.databind.Module in com.fasterxml.jackson.databind and class java.lang.Module in java.lang match
[ERROR]
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project
 visallo-client-api: Compilation failure
/C:/Users/utente-05/visallo/web/client-api/src/main/java/org/visallo/web/clientapi/util/ObjectMapperFactory.java:[25,20] reference to Module is ambiguous
  both class com.fasterxml.jackson.databind.Module in com.fasterxml.jackson.databind and class java.lang.Module in java.lang match

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/C:/Users/utente-05/visallo/web/client-api/src/main/java/org/visallo/web/clientapi/util/ObjectMapperFactory.java:[25,20] reference to Module is ambiguous
  both class com.fasterxml.jackson.databind.Module in com.fasterxml.jackson.databind and class java.lang.Module in java.lang match

        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :visallo-client-api

is anyone able to help me? 

thanks 

Lorenzo

**Comment by Calahan76** [comment]
Hi,
I have the same issue (or at least same error message) with CentOS:

Maven home: /opt/apache-maven-3.5.0
Java version: 9, vendor: Oracle Corporation
Java home: /usr/java/jdk-9
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-693.2.2.el7.x86_64", arch: "amd64", family: "unix"

Git cloned on Sept 25.

**Comment by mwizeman** [comment]
Hello. Thanks for providing all of the information for your systems. We don't currently only build and deploy using Java 8. Would it be possible for you to install Java 8 and try again? Thanks!
