### ISSUE TITLE
Failure when running Visallo on VPS Ubuntu 16.04

### ISSUE THREAD

**Issue by lorenzoromani1983** [visallo/visallo#1350]
Hi. I am trying to set up Visallo running on a digital ocean web server equipped with Ubuntu 16.04.
However, i get stuck with this error log:

[INFO] Running 'webpack.js ' in /root/visallo/web/plugins/graph-product/src/main                                                                                                             /resources/org/visallo/web/product/graph
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Visallo: Maven Archetype ........................... SUCCESS [  2.098 s]
[INFO] Visallo: Web: Client API ........................... SUCCESS [  1.758 s]
[INFO] Visallo ............................................ SUCCESS [  1.280 s]
[INFO] Visallo: Core Group ................................ SUCCESS [  0.076 s]
[INFO] Visallo: Core ...................................... SUCCESS [  9.478 s]
[INFO] Visallo: Common .................................... SUCCESS [  0.136 s]
[INFO] Visallo: Common: RDF ............................... SUCCESS [  0.381 s]
[INFO] Visallo: Config File Examples ...................... SUCCESS [  0.071 s]
[INFO] Visallo: Core: Plugins ............................. SUCCESS [  0.059 s]
[INFO] Visallo: Core: Plugin: Model: Queue: InMemory ...... SUCCESS [  0.303 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium ............ SUCCESS [  1.679 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium InMemory ... SUCCESS [  0.292 s]
[INFO] Visallo: Core Test ................................. SUCCESS [  0.313 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium Elasticsearch SUCCESS [  0.499 s]
[INFO] Visallo: Core: Plugin: Model: Vertexium Tests ...... SUCCESS [  0.116 s]
[INFO] Visallo: Tools ..................................... SUCCESS [  0.049 s]
[INFO] Visallo: Tools: Import ............................. SUCCESS [  0.319 s]
[INFO] Visallo: Tools: RDF Import ......................... SUCCESS [  0.268 s]
[INFO] Visallo: Tools: OWL ................................ SUCCESS [  0.220 s]
[INFO] Visallo: Tools: Run GPW ............................ SUCCESS [  0.233 s]
[INFO] Visallo: Tools: Migrations ......................... SUCCESS [  0.080 s]
[INFO] Visallo: Tools - Migration Core .................... SUCCESS [  0.592 s]
[INFO] Visallo: Tools - Migration Workspace to Work Product SUCCESS [  0.210 s]
[INFO] Visallo: Tools - Bump Graph Version ................ SUCCESS [  0.301 s]
[INFO] Visallo: Tools: CLI ................................ SUCCESS [  0.348 s]
[INFO] Visallo: Dev ....................................... SUCCESS [  0.128 s]
[INFO] Visallo: Dev: CLI .................................. SUCCESS [  0.161 s]
[INFO] Visallo: Web ....................................... SUCCESS [  0.063 s]
[INFO] Visallo: Web: Base ................................. SUCCESS [  1.332 s]
[INFO] Visallo: Web: Server ............................... SUCCESS [  0.085 s]
[INFO] Visallo: Web: Server: Base ......................... SUCCESS [  0.251 s]
[INFO] Visallo: Web: Server: Tomcat ....................... SUCCESS [  0.492 s]
[INFO] Visallo: Web: Plugin Base .......................... SUCCESS [  1.023 s]
[INFO] Visallo: Web: Plugin: Username-only Authentication . SUCCESS [  0.852 s]
[INFO] Visallo: Web: Plugin: Admin User Tools ............. SUCCESS [  1.047 s]
[INFO] Visallo: Web: Plugin: Admin User Tools: User Property Authorization SUCCESS [  0.824 s]
[INFO] Visallo: Web: Plugin: Admin User Tools: User Property Privileges SUCCESS [  0.894 s]
[INFO] Visallo: Web: Plugins: Admin Import RDF ............ SUCCESS [  1.116 s]
[INFO] Visallo: Web: Plugin: Graph Work Product ........... FAILURE [01:14 min]
[INFO] Visallo: Web: Plugin: Map Work Product ............. SKIPPED
[INFO] Visallo: Web: Plugins: Table ....................... SKIPPED
[INFO] Visallo: Core: Plugin: Ingest: Cloud: S3 ........... SKIPPED
[INFO] Visallo: Web: Structured Ingest: Core .............. SKIPPED
[INFO] Visallo: Web: Structured Ingest: Spreadsheets ...... SKIPPED
[INFO] Visallo: Web: Structured Ingest: Parquet ........... SKIPPED
[INFO] Visallo: GraphPropertyWorker ....................... SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin Base .......... SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: E-Mail Address Extractor SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Mime Type Ontology Mapper SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Phone Number Extractor SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Tika Mime Type Mapper SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Tika Text Extractor SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Zip Code Extractor SKIPPED
[INFO] Visallo: Dev: Tomcat Server ........................ SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugin: Search Reindex SKIPPED
[INFO] Visallo: GraphPropertyWorker: Plugins .............. SKIPPED
[INFO] visallo-tools-ontology-ingest ...................... SKIPPED
[INFO] visallo-tools-ontology-ingest-common ............... SKIPPED
[INFO] visallo-tools-ontology-ingest-codegen .............. SKIPPED
[INFO] Visallo: Tools: Reindex ............................ SKIPPED
[INFO] Visallo: Tools - Migration Predefined to Dynamic Ontology SKIPPED
[INFO] Visallo: Web: Base Test ............................ SKIPPED
[INFO] Visallo: Web: War .................................. SKIPPED
[INFO] Visallo: Web: Plugin: Username/Password Authentication SKIPPED
[INFO] Visallo: Web: Plugin: Change Email ................. SKIPPED
[INFO] Visallo: Web: Plugin: Change Password .............. SKIPPED
[INFO] Visallo: Web: Plugins .............................. SKIPPED
[INFO] Visallo: Web: Structured Ingest .................... SKIPPED
[INFO] Visallo: Web: Client API: Code Generator ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:48 min
[INFO] Finished at: 2017-10-05T08:18:48+00:00
[INFO] Final Memory: 46M/112M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:webpack (webpack build) on project visallo-web-product-graph                                                    : Failed to run task: 'webpack.js ' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137)                                                     -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:webpack (web                                                    pack build) on project visallo-web-product-graph: Failed to run task
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:121)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'webpack.js ' failed.
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:63)
        at com.github.eirslett.maven.plugins.frontend.mojo.WebpackMojo.execute(WebpackMojo.java:64)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:115)
        ... 22 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutionException: org.apache.commons.exec.ExecuteException: Process ex                                                    ited with an error: 137 (Exit value: 137)
        at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute(ProcessExecutor.java:82)
        at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput(ProcessExecutor.java:64)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeExecutor.executeAndRedirectOutput(NodeExecutor.java:29)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:58)
        ... 24 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute(ProcessExecutor.java:74)
        ... 27 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :visallo-web-product-graph
root@ubuntu-512mb-fra1-01:~/visallo#

**Comment by nykzero** [comment]
I had this problem too, I checked the system logs and found I was getting an out of memory error.  In my case I created a swap file and it's running fine.
