### ISSUE TITLE
Adding the sample ontology path  in config 

### ISSUE THREAD

**Issue by R2D2-fwks** [visallo/visallo#1466]
Hi Facing the issue that after reading the documentation. I added two lines in the visallo.properties file 
     `repository.ontology.owl.default.iri=http://visallo.org/sample
     repository.ontology.owl.default.dir=$VISALLO_DIR/config/ontology-sample`
and getting the error as  
```
Caused by: org.visallo.core.exception.VisalloException: you cannot specify both dir and file for repository.ontology.owl.default
	at org.visallo.core.model.ontology.OntologyRepositoryBase.lambda$loadOntologies$0(OntologyRepositoryBase.java:130) ~[classes/:?]
	at org.visallo.core.model.lock.SingleJvmLockRepository$1.run(SingleJvmLockRepository.java:36) ~[classes/:?]
	at org.visallo.core.model.lock.LockRepository.lock(LockRepository.java:30) ~[classes/:?]
	at org.visallo.core.model.ontology.OntologyRepositoryBase.loadOntologies(OntologyRepositoryBase.java:101) ~[classes/:?]
	at org.visallo.vertexium.model.ontology.InMemoryOntologyRepository.<init>(InMemoryOntologyRepository.java:65) ~[classes/:?]
	at org.visallo.vertexium.model.ontology.InMemoryOntologyRepository$$FastClassByGuice$$4c3c2bfe.newInstance(<generated>) ~[classes/:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054) ~[guice-4.1.0.jar:?]
	at org.visallo.core.bootstrap.InjectHelper.getInstance(InjectHelper.java:55) ~[classes/:?]
	at org.visallo.core.bootstrap.VisalloBootstrap$ConfigurableProvider.get(VisalloBootstrap.java:348) ~[classes/:?]
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054) ~[guice-4.1.0.jar:?]
	at org.visallo.core.bootstrap.InjectHelper.getInstance(InjectHelper.java:55) ~[classes/:?]
	... 11 more
2017-12-05 14:15:59.785/IST DEBUG [:] [core.bootstrap.InjectHelper] getInstance of class: org.visallo.core.util.ShutdownService
2017-12-05 14:15:59.786/IST INFO  [:] [core.util.ShutdownService] Shutdown: org.visallo.core.model.lock.SingleJvmLockRepository
2017-12-05 14:15:59.786/IST INFO  [:] [core.util.ShutdownService] Shutdown: org.visallo.core.bootstrap.GraphShutdownListener
2017-12-05 14:15:59.804/IST DEBUG [:] [vertexium.elasticsearch5.Elasticsearch5SearchIndex] loading index info for visallo
ternal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at org.visallo.core.bootstrap.InjectHelper.getInstance(InjectHelper.java:55)
	... 11 more
Caused by: org.visallo.core.exception.VisalloException: Could not create class: org.visallo.vertexium.model.ontology.InMemoryOntologyRepository
	at org.visallo.core.bootstrap.InjectHelper.getInstance(InjectHelper.java:58)
	at org.visallo.core.bootstrap.VisalloBootstrap$ConfigurableProvider.get(VisalloBootstrap.java:348)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 13 more
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, org.visallo.core.exception.VisalloException: Failed to run in lock
  at org.visallo.vertexium.model.ontology.InMemoryOntologyRepository.<init>(InMemoryOntologyRepository.java:57)
  at org.visallo.vertexium.model.ontology.InMemoryOntologyRepository.class(InMemoryOntologyRepository.java:37)
  while locating org.visallo.vertexium.model.ontology.InMemoryOntologyRepository

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at org.visallo.core.bootstrap.InjectHelper.getInstance(InjectHelper.java:55)
	... 26 more
Caused by: org.visallo.core.exception.VisalloException: Failed to run in lock
	at org.visallo.core.model.lock.SingleJvmLockRepository$1.run(SingleJvmLockRepository.java:39)
	at org.visallo.core.model.lock.LockRepository.lock(LockRepository.java:30)
	at org.visallo.core.model.ontology.OntologyRepositoryBase.loadOntologies(OntologyRepositoryBase.java:101)
	at org.visallo.vertexium.model.ontology.InMemoryOntologyRepository.<init>(InMemoryOntologyRepository.java:65)
	at org.visallo.vertexium.model.ontology.InMemoryOntologyRepository$$FastClassByGuice$$4c3c2bfe.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
```

**Comment by sfeng88** [comment]
do you have `repository.ontology.owl.default.file` somewhere else in any of your configs? You can't have both.

**Comment by R2D2-fwks** [comment]
Yes i was adding it in visallo.properties file , as it was there in the x-visallo.properties file .Got it i have dig around to know which config file contains what . Thanks Closing the issue.
